import { getAuthContext } from "@/lib/auth/auth-utils";
import { db } from "@/db";
import { outboundEmails, contacts, companies, sequenceEnrollments } from "@/db/schema";
import { eq, and, inArray, sql, isNull } from "drizzle-orm";
import { recordAutonomyEvent } from "@/lib/guardrails/trust-score";
import { recordFlywheelCandidate } from "@/lib/evals/flywheel";

/** The contact facts that condition a flywheel example's input. */
type ContactMeta = { title: string | null; industry: string | null };

/**
 * Batch-resolve the conditioning facts (role + industry) for the approved
 * contacts, tenant-scoped. Safe to put in the few-shot input because reads are
 * now tenant-isolated (getFewShotExamples filters by the tenant tag) — an
 * example only ever surfaces to the tenant that produced it.
 */
async function fetchContactMeta(
  contactIds: Array<string | null>,
  tenantId: string,
): Promise<Map<string, ContactMeta>> {
  const ids = [...new Set(contactIds.filter((id): id is string => !!id))];
  if (ids.length === 0) return new Map();
  const rows = await db
    .select({ id: contacts.id, title: contacts.title, industry: companies.industry })
    .from(contacts)
    .leftJoin(companies, eq(contacts.companyId, companies.id))
    .where(and(eq(contacts.tenantId, tenantId), inArray(contacts.id, ids)));
  return new Map(rows.map((r) => [r.id, { title: r.title, industry: r.industry }]));
}

/**
 * Build the (input, output) pair recorded into the drafting flywheel from an
 * approved outbound email. When the contact's role is known the input is a
 * SITUATION-conditioned prompt ("a cold email to a VP Sales in SaaS") — a
 * better demonstration for future drafts to a similar prospect. Without a role
 * it falls back to the contactId form so title-less contacts still stay
 * distinct under recordFlywheelCandidate's input-equality dedup. The output is
 * the approved subject + body — the exemplar to imitate. (The TRUE generation
 * context would be snapshotted at draft time, which needs a prod migration —
 * still blocked; this reconstructs the salient facts at approval instead.)
 */
function draftFlywheelPair(
  row: {
    subject: string | null;
    bodyHtml: string | null;
    contactId: string | null;
    stepNumber: number | null;
  },
  meta?: ContactMeta,
): { input: string; output: string } {
  const stepSuffix = row.stepNumber != null ? ` (step ${row.stepNumber})` : "";
  const input = meta?.title
    ? `Draft a cold email to a ${meta.title}${meta.industry ? ` in ${meta.industry}` : ""}${stepSuffix}`
    : `Draft email to contact ${row.contactId || "unknown"}${stepSuffix}`;
  return {
    input,
    output: `Subject: ${row.subject || ""}\n\n${row.bodyHtml || ""}`,
  };
}

/**
 * The flywheel agent an approved draft belongs to. Campaign/sequence drafts are
 * GENERATED by personalizeStepEmail under agentId "send-sequence-step"
 * (sequence-generator.ts) and carry an enrollmentId; the interactive path is
 * "draft-email". Capturing under the GENERATING agent is load-bearing:
 * getFewShotExamples / applyLearnedContext read by agentId, so a campaign
 * approval recorded as "draft-email" would feed a different surface and never
 * close the loop for the sequence generator that actually produced it.
 */
function draftAgentId(row: { enrollmentId: string | null }): string {
  return row.enrollmentId ? "send-sequence-step" : "draft-email";
}

export async function GET(req: Request) {
  const authCtx = await getAuthContext();
  if (!authCtx) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const status = searchParams.get("status") || "draft";
  const sequenceId = searchParams.get("sequenceId");

  // If sequenceId provided, get enrollment IDs for that sequence
  let enrollmentIdFilter: string[] | null = null;
  if (sequenceId) {
    const enrollments = await db
      .select({ id: sequenceEnrollments.id })
      .from(sequenceEnrollments)
      .where(eq(sequenceEnrollments.sequenceId, sequenceId));
    enrollmentIdFilter = enrollments.map((e) => e.id);
    if (enrollmentIdFilter.length === 0) {
      return Response.json({ emails: [] });
    }
  }

  const conditions = [eq(outboundEmails.tenantId, authCtx.tenantId)];
  if (status !== "all") {
    conditions.push(eq(outboundEmails.status, status as any));
  }

  const allEmails = await db
    .select()
    .from(outboundEmails)
    .where(and(...conditions))
    .orderBy(sql`created_at DESC`)
    .limit(500);

  // Filter by sequence enrollments if needed
  const emails = enrollmentIdFilter
    ? allEmails.filter((e) => e.enrollmentId && enrollmentIdFilter!.includes(e.enrollmentId))
    : allEmails;

  // Enrich with contact info
  const contactIds = [...new Set(emails.map((e) => e.contactId).filter(Boolean))];
  const contactList =
    contactIds.length > 0
      ? await db
          .select()
          .from(contacts)
          .where(and(eq(contacts.tenantId, authCtx.tenantId), inArray(contacts.id, contactIds as string[]), isNull(contacts.deletedAt)))
      : [];
  const contactMap = Object.fromEntries(contactList.map((c) => [c.id, c]));

  const enrichedEmails = emails.map((e) => ({
    ...e,
    contact: e.contactId ? contactMap[e.contactId] || null : null,
  }));

  return Response.json({ emails: enrichedEmails });
}

export async function PUT(req: Request) {
  const authCtx = await getAuthContext();
  if (!authCtx) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const { emailId, action, subject, bodyHtml } = body;

  if (!emailId || !action) {
    return Response.json({ error: "emailId and action required" }, { status: 400 });
  }

  switch (action) {
    case "approve": {
      const hasEdits = !!(subject || bodyHtml);

      await db
        .update(outboundEmails)
        .set({
          status: "queued",
          queuedAt: new Date(),
          ...(subject && { subject }),
          ...(bodyHtml && { bodyHtml }),
          updatedAt: new Date(),
        })
        .where(and(eq(outboundEmails.id, emailId), eq(outboundEmails.tenantId, authCtx.tenantId)));

      // Trust signal: approved_no_edit is the strongest positive signal;
      // approved_with_edit is weaker (the user still had to fix something).
      const eventType = hasEdits ? "approved_with_edit" : "approved_no_edit";
      recordAutonomyEvent({
        tenantId: authCtx.tenantId,
        userId: authCtx.userId,
        eventType,
        entityRef: `email:${emailId}`,
        reason: hasEdits
          ? "Email approved with user edits"
          : "Email approved without edits",
      }).catch(() => {
        // Swallow — trust scoring must never block the approval flow.
      });

      // Flywheel: capture the approved draft as a few-shot / distillation
      // example. An unedited approval ("user_approved") says the AI got it
      // right; an approval WITH edits ("user_edited") captures the founder's
      // corrected final — the strongest teaching signal, and the only one
      // with fuel from the very first edit (no deal volume or outcome
      // resolution needed). Trust scoring above still treats an edit as
      // weaker autonomy; here the edited FINAL is a first-class example.
      // The row was just updated above, so this re-fetch returns the edited
      // final whenever hasEdits is true.
      const [emailRow] = await db
        .select({
          subject: outboundEmails.subject,
          bodyHtml: outboundEmails.bodyHtml,
          contactId: outboundEmails.contactId,
          stepNumber: outboundEmails.stepNumber,
          enrollmentId: outboundEmails.enrollmentId,
        })
        .from(outboundEmails)
        .where(
          and(
            eq(outboundEmails.id, emailId),
            eq(outboundEmails.tenantId, authCtx.tenantId),
          ),
        )
        .limit(1);

      if (emailRow) {
        const meta = await fetchContactMeta([emailRow.contactId], authCtx.tenantId).catch(
          () => new Map<string, ContactMeta>(),
        );
        const { input, output } = draftFlywheelPair(
          emailRow,
          emailRow.contactId ? meta.get(emailRow.contactId) : undefined,
        );
        recordFlywheelCandidate(
          draftAgentId(emailRow),
          input,
          output,
          authCtx.tenantId,
          hasEdits ? "user_edited" : "user_approved",
        ).catch(() => {
          // Swallow — flywheel is best-effort, never blocks approval.
        });
      }
      break;
    }
    case "skip": {
      await db
        .update(outboundEmails)
        .set({ status: "skipped", updatedAt: new Date() })
        .where(and(eq(outboundEmails.id, emailId), eq(outboundEmails.tenantId, authCtx.tenantId)));
      break;
    }
    case "edit": {
      if (subject || bodyHtml) {
        await db
          .update(outboundEmails)
          .set({
            ...(subject && { subject }),
            ...(bodyHtml && { bodyHtml }),
            updatedAt: new Date(),
          })
          .where(and(eq(outboundEmails.id, emailId), eq(outboundEmails.tenantId, authCtx.tenantId)));
      }
      break;
    }
  }

  return Response.json({ success: true });
}

// Bulk approve
export async function POST(req: Request) {
  const authCtx = await getAuthContext();
  if (!authCtx) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const { emailIds, action } = body;

  if (!emailIds || !Array.isArray(emailIds) || !action) {
    return Response.json({ error: "emailIds array and action required" }, { status: 400 });
  }

  if (action === "approve_all") {
    await db
      .update(outboundEmails)
      .set({ status: "queued", queuedAt: new Date(), updatedAt: new Date() })
      .where(
        and(
          eq(outboundEmails.tenantId, authCtx.tenantId),
          inArray(outboundEmails.id, emailIds),
          eq(outboundEmails.status, "draft")
        )
      );

    // Bulk approval = approved_no_edit for each email. Emit one trust
    // event per email to keep the audit trail granular. Fire-and-forget
    // so the response isn't blocked by N sequential writes.
    Promise.allSettled(
      emailIds.map((id: string) =>
        recordAutonomyEvent({
          tenantId: authCtx.tenantId,
          userId: authCtx.userId,
          eventType: "approved_no_edit",
          entityRef: `email:${id}`,
          reason: "Email approved via bulk approve_all",
        }),
      ),
    ).catch(() => {});

    // Flywheel: THIS is the approval path the review UI actually calls
    // (campaign-wizard bulk-approves via POST approve_all). Record each
    // approved draft as a `user_approved` few-shot / distillation example —
    // the UI has no inline edit, so a bulk approval is always an unedited
    // accept. Best-effort: a failure here must never block the approval.
    try {
      const approvedRows = await db
        .select({
          subject: outboundEmails.subject,
          bodyHtml: outboundEmails.bodyHtml,
          contactId: outboundEmails.contactId,
          stepNumber: outboundEmails.stepNumber,
          enrollmentId: outboundEmails.enrollmentId,
        })
        .from(outboundEmails)
        .where(
          and(
            eq(outboundEmails.tenantId, authCtx.tenantId),
            inArray(outboundEmails.id, emailIds),
          ),
        );

      const meta = await fetchContactMeta(
        approvedRows.map((r) => r.contactId),
        authCtx.tenantId,
      );

      Promise.allSettled(
        approvedRows.map((row) => {
          const { input, output } = draftFlywheelPair(
            row,
            row.contactId ? meta.get(row.contactId) : undefined,
          );
          return recordFlywheelCandidate(
            draftAgentId(row),
            input,
            output,
            authCtx.tenantId,
            "user_approved",
          );
        }),
      ).catch(() => {});
    } catch {
      // Swallow — flywheel is best-effort, never blocks bulk approval.
    }
  }

  return Response.json({ success: true, count: emailIds.length });
}
