/**
 * Inbound sender classification — deterministic, pure, free.
 *
 * The product was treating "an email arrived" as "a person wants to buy from
 * us", so receipts, SaaS notifications and newsletters from services the
 * founder *subscribes to* surfaced as warm/hot leads. This is the first,
 * cheapest stage of the inbound-lead funnel (see
 * `_specs/inbound-lead-recognition/`): separate machine-sent mail from a real
 * human before anything is promoted to a lead.
 *
 * Scope (deliberate): this module answers ONLY "was this typed by a human, or
 * generated by a system?" — a question with a deterministic, protocol-level
 * answer. It does NOT decide the commercial relationship (prospect that could
 * buy us vs. a vendor we pay) — that is a semantic judgement resolved by an
 * LLM over the tenant's ICP in tranche 2, never a hardcoded vendor list.
 *
 * On `feedback_no-hardcoded-matching`: the role local-parts below
 * (`noreply`, `mailer-daemon`, `postmaster`, …) are **email-addressing
 * conventions** — `postmaster` is mandated by RFC 5321, `List-Unsubscribe` by
 * RFC 2369/8058, `Auto-Submitted` by RFC 3834. They are protocol facts, the
 * same signals every MTA/ESP/anti-spam stack uses, NOT a business-domain
 * classification (industries, job titles) that the rule targets. The semantic
 * brain stays in the LLM stage.
 *
 * Pure: no DB, no network, no ambient clock. Never throws — malformed input
 * fails open to "human/unknown" so we capture rather than silently drop.
 */

export type SenderType =
  | "human"
  | "automated_transactional"
  | "automated_marketing"
  | "vendor"
  | "internal"
  | "unknown";

export interface SenderClassification {
  senderType: SenderType;
  /** A real lead requires a human — true blocks lead promotion + auto-create. */
  isMachineSent: boolean;
  /** Mass/marketing mail (carries an unsubscribe affordance). */
  isBulk: boolean;
  /** Local-part is a role/functional address (incl. soft roles like support@). */
  isRoleAddress: boolean;
  /** Product-language reasons, surfaced in the "why" line + audit trail. */
  reasons: string[];
}

export interface ClassifyInboundInput {
  /** Raw `From` header ("Name <addr>") or a bare address. */
  fromHeader: string;
  subject?: string | null;
  text?: string | null;
  /** RFC headers when the call-site has them (EmailEngine/IMAP). Optional. */
  headers?: Record<string, string> | null;
}

/**
 * Hard machine local-parts: unambiguously system-generated. An exact
 * (separator-insensitive) match here ⇒ machine-sent. Includes FR variants
 * (`nepasrepondre`) for the francophone context.
 */
const HARD_MACHINE_LOCALPARTS = new Set<string>([
  "noreply",
  "noreplies",
  "donotreply",
  "donotrespond",
  "nepasrepondre",
  "mailerdaemon",
  "mailer",
  "bounce",
  "bounces",
  "postmaster",
  "notification",
  "notifications",
  "notify",
  "notifier",
  "automated",
  "autoreply",
  "autoresponder",
  "system",
  "alert",
  "alerts",
  "newsletter",
  "newsletters",
  "infolettre",
  "news",
  "digest",
  "updates",
  "mailbot",
]);

/**
 * Unambiguous machine prefixes — match even with a suffix (`noreply-account`,
 * `noreply2`, `nepasrepondre.pilae`). Kept tiny and unambiguous so a real
 * person ("Norbert", "Noreen Reply") never trips it.
 */
const HARD_MACHINE_PREFIXES = [
  "noreply",
  "donotreply",
  "donotrespond",
  "nepasrepondre",
  "mailerdaemon",
  "autoreply",
  "autoresponder",
];

/** Marketing-flavoured roles → automated_marketing rather than transactional. */
const MARKETING_LOCALPARTS = new Set<string>([
  "newsletter",
  "newsletters",
  "infolettre",
  "news",
  "digest",
  "updates",
  "marketing",
]);

/**
 * Soft functional roles: often automated, but `support@`/`sales@` at a small
 * shop can be a real human replying. These set `isRoleAddress` (a signal for
 * the tranche-2 LLM) but do NOT alone mark machine-sent — we never want to
 * drop a possible human. They are NOT a business classification; they are
 * shared-mailbox conventions.
 */
const SOFT_ROLE_LOCALPARTS = new Set<string>([
  "support",
  "billing",
  "facturation",
  "comptabilite",
  "invoice",
  "invoices",
  "receipt",
  "receipts",
  "account",
  "accounts",
  "hello",
  "bonjour",
  "team",
  "equipe",
  "info",
  "contact",
  "contacto",
  "sales",
  "commercial",
  "help",
  "admin",
  "office",
  "members",
  "community",
  "care",
  "service",
  "services",
  "security",
]);

/** "John Doe <john@example.com>" / "john@example.com" → "john" (local-part). */
function extractLocalPart(fromHeader: string): string {
  const m = fromHeader?.match(/<([^>]+)>/);
  const addr = (m ? m[1] : fromHeader || "").trim().toLowerCase();
  const at = addr.lastIndexOf("@");
  if (at <= 0) return "";
  return addr.slice(0, at);
}

/** Lower-case all header keys once so lookups are case-insensitive (R5). */
function normalizeHeaders(
  headers: Record<string, string> | null | undefined,
): Record<string, string> {
  const out: Record<string, string> = {};
  if (!headers) return out;
  for (const [k, v] of Object.entries(headers)) {
    if (typeof k === "string" && typeof v === "string") out[k.toLowerCase()] = v;
  }
  return out;
}

/**
 * Classify an inbound sender as machine vs human using the message envelope
 * and RFC headers. First hard signal wins; everything else is "human".
 */
export function classifyInboundSender(
  input: ClassifyInboundInput,
): SenderClassification {
  const reasons: string[] = [];
  const headers = normalizeHeaders(input.headers);

  // ── RFC header signals (strongest, protocol-level) ──────────────────
  const hasListHeader =
    "list-unsubscribe" in headers ||
    "list-id" in headers ||
    "list-unsubscribe-post" in headers;
  const precedence = (headers["precedence"] || "").toLowerCase();
  const precedenceBulk = /\b(bulk|list|junk)\b/.test(precedence);
  const autoSubmitted = (headers["auto-submitted"] || "").toLowerCase();
  const isAutoSubmitted = autoSubmitted !== "" && autoSubmitted !== "no";
  const hasAutoSuppress = "x-auto-response-suppress" in headers;

  // ── Role local-part ────────────────────────────────────────────────
  const localPart = extractLocalPart(input.fromHeader || "");
  const base = localPart.split("+")[0]; // strip subaddress tag
  const squished = base.replace(/[._-]/g, "");
  const isHardPrefix = HARD_MACHINE_PREFIXES.some((p) => squished.startsWith(p));
  const isHardExact = HARD_MACHINE_LOCALPARTS.has(squished);
  const isHardRole = isHardPrefix || isHardExact;
  const isMarketingRole = MARKETING_LOCALPARTS.has(squished);
  const isSoftRole = SOFT_ROLE_LOCALPARTS.has(squished);
  const isRoleAddress = isHardRole || isSoftRole;

  // ── Body-level bulk hint (weak, contributory only) ──────────────────
  const haystack = `${input.subject || ""}\n${input.text || ""}`.toLowerCase();
  const bodyBulkHint =
    /\bunsubscribe\b/.test(haystack) ||
    /se d[ée]sinscrire/.test(haystack) ||
    /se d[ée]sabonner/.test(haystack) ||
    /view (this )?(email )?in (your )?browser/.test(haystack) ||
    /voir (cet )?(e-?mail )?dans (le|votre) navigateur/.test(haystack);

  // ── Resolve ─────────────────────────────────────────────────────────
  const isBulk = hasListHeader || precedenceBulk || isMarketingRole || bodyBulkHint;

  if (hasListHeader) reasons.push("bulk mailing-list headers");
  if (precedenceBulk) reasons.push(`precedence: ${precedence}`);
  if (isAutoSubmitted) reasons.push("auto-submitted (machine-generated)");
  if (hasAutoSuppress) reasons.push("auto-response-suppress header");
  if (isHardRole) reasons.push(`automated sender address (${base || "unknown"})`);
  else if (isMarketingRole) reasons.push(`marketing sender address (${base})`);
  else if (isSoftRole) reasons.push(`shared/role mailbox (${base})`);
  if (bodyBulkHint && !hasListHeader) reasons.push("unsubscribe link in body");

  const machineByHeader = hasListHeader || precedenceBulk || isAutoSubmitted || hasAutoSuppress;
  const isMachineSent = machineByHeader || isHardRole;

  let senderType: SenderType;
  if (!localPart) {
    senderType = "unknown";
  } else if (hasListHeader || isMarketingRole || (precedenceBulk && isBulk)) {
    senderType = "automated_marketing";
  } else if (isMachineSent) {
    senderType = "automated_transactional";
  } else if (isSoftRole) {
    // Possibly a human at a shared mailbox — defer the verdict to the LLM stage.
    senderType = "unknown";
  } else {
    senderType = "human";
  }

  return { senderType, isMachineSent, isBulk, isRoleAddress, reasons };
}
