"use client";

import { useState, useEffect, useCallback } from "react";
import { Card, CardBody } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/ui/page-header";
import { FileBarChart, TrendingUp, CalendarDays, Trophy, Loader2, Copy, Check, Clock, ClipboardCopy, Timer } from "lucide-react";
import { RevenueForecast } from "./_revenue-forecast";
import { CohortInsights } from "./_cohort-insights";

interface ReportData {
  title: string;
  summary: string;
  sections: Array<{ heading: string; content: string }>;
  metrics: Array<{ label: string; value: string }>;
  recommendations: string[];
}

interface HistoryEntry {
  id: string;
  type: string;
  title: string;
  generatedAt: string;
  report: ReportData;
}

// History was stored under a single fixed key, so on a shared machine the full
// AI report content (real tenant numbers) leaked to the next tenant/user and
// survived logout. Scope the key by tenant id; persist only once it is known.
const HISTORY_KEY_PREFIX = "elevay-report-history";
const LEGACY_HISTORY_KEY = "elevay-report-history";
const MAX_HISTORY = 5;

function loadHistory(key: string | null): HistoryEntry[] {
  if (typeof window === "undefined" || !key) return [];
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveHistory(key: string | null, entries: HistoryEntry[]) {
  // No tenant scope resolved yet → keep history in-memory only, never persist
  // (a fixed key is what caused the cross-tenant leak).
  if (typeof window === "undefined" || !key) return;
  try {
    localStorage.setItem(key, JSON.stringify(entries.slice(0, MAX_HISTORY)));
  } catch {
    // localStorage full or unavailable
  }
}

function reportToMarkdown(report: ReportData): string {
  const lines: string[] = [];
  lines.push(`# ${report.title}`);
  lines.push("");
  lines.push(report.summary);
  lines.push("");

  if (report.metrics.length > 0) {
    lines.push("## Key Metrics");
    lines.push("");
    lines.push("| Metric | Value |");
    lines.push("|--------|-------|");
    for (const m of report.metrics) {
      lines.push(`| ${m.label} | ${m.value} |`);
    }
    lines.push("");
  }

  for (const section of report.sections) {
    lines.push(`## ${section.heading}`);
    lines.push("");
    lines.push(section.content);
    lines.push("");
  }

  if (report.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    for (const rec of report.recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by Elevay on ${new Date().toLocaleDateString()}*`);

  return lines.join("\n");
}

const PROGRESS_STEPS = [
  "Collecting pipeline data...",
  "Analyzing deal patterns...",
  "Building report structure...",
  "Generating insights with AI...",
  "Formatting results...",
];

const reportTypes = [
  {
    type: "pipeline" as const,
    title: "Pipeline Report",
    description:
      "Executive overview of your pipeline health, key metrics, stalled deals, and risks.",
    icon: TrendingUp,
    badgeLabel: "Pipeline",
    badgeVariant: "info" as const,
  },
  {
    type: "weekly" as const,
    title: "Weekly Report",
    description:
      "Summary of the last 7 days: activities, deals created/won/lost, and priorities for next week.",
    icon: CalendarDays,
    badgeLabel: "Activity",
    badgeVariant: "success" as const,
  },
  {
    type: "winloss" as const,
    title: "Win/Loss Report",
    description:
      "Patterns in your won and lost deals with data-driven recommendations to improve close rates.",
    icon: Trophy,
    badgeLabel: "Analysis",
    badgeVariant: "warning" as const,
  },
];

export default function ReportsPage() {
  const [loading, setLoading] = useState<string | null>(null);
  const [report, setReport] = useState<ReportData | null>(null);
  const [activeType, setActiveType] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [progressStep, setProgressStep] = useState(0);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [historyKey, setHistoryKey] = useState<string | null>(null);
  const [schedulingType, setSchedulingType] = useState<string | null>(null);
  const [scheduleSuccess, setScheduleSuccess] = useState<string | null>(null);

  // Resolve a tenant-scoped history key from the session, purge the old
  // unscoped key (the cross-tenant leak vector), then load THIS tenant's history.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      // Best-effort: clear the legacy shared key so previously-leaked report
      // content doesn't linger on the machine.
      try { localStorage.removeItem(LEGACY_HISTORY_KEY); } catch { /* ignore */ }
      let key: string | null = null;
      try {
        const res = await fetch("/api/auth/session");
        const session = res.ok ? await res.json() : null;
        const scope = session?.tenantId ?? session?.user?.id ?? null;
        key = scope ? `${HISTORY_KEY_PREFIX}:${scope}` : null;
      } catch {
        key = null;
      }
      if (cancelled) return;
      setHistoryKey(key);
      setHistory(loadHistory(key));
    })();
    return () => { cancelled = true; };
  }, []);

  // Progress animation while loading
  useEffect(() => {
    if (!loading) {
      setProgressStep(0);
      return;
    }
    setProgressStep(0);
    const interval = setInterval(() => {
      setProgressStep((prev) => {
        if (prev >= PROGRESS_STEPS.length - 1) return prev;
        return prev + 1;
      });
    }, 2500);
    return () => clearInterval(interval);
  }, [loading]);

  async function generateReport(type: string) {
    setLoading(type);
    setActiveType(type);
    setError(null);
    setReport(null);

    try {
      const res = await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || `Failed to generate report (${res.status})`);
      }

      const data = await res.json();
      setReport(data.report);

      // Save to history
      const entry: HistoryEntry = {
        id: `${type}-${Date.now()}`,
        type,
        title: data.report.title,
        generatedAt: new Date().toISOString(),
        report: data.report,
      };
      const updated = [entry, ...history.filter((h) => h.id !== entry.id)].slice(0, MAX_HISTORY);
      setHistory(updated);
      saveHistory(historyKey, updated);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to generate report");
    } finally {
      setLoading(null);
    }
  }

  function loadFromHistory(entry: HistoryEntry) {
    setReport(entry.report);
    setActiveType(entry.type);
    setError(null);
  }

  const copyAsMarkdown = useCallback(() => {
    if (!report) return;
    const md = reportToMarkdown(report);
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [report]);

  async function scheduleWeekly(type: string) {
    setSchedulingType(type);
    setScheduleSuccess(null);
    try {
      const res = await fetch("/api/reports/schedule", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type, schedule: "weekly" }),
      });
      if (res.ok) {
        setScheduleSuccess(type);
        setTimeout(() => setScheduleSuccess(null), 3000);
      } else {
        const data = await res.json().catch(() => ({}));
        setError(data.error || "Failed to schedule report");
      }
    } catch {
      setError("Failed to schedule report");
    } finally {
      setSchedulingType(null);
    }
  }

  return (
    <div className="flex h-full flex-col animate-content-in">
      <PageHeader
        icon={<FileBarChart size={16} />}
        title="Reports"
        subtitle="AI-generated executive reports"
      />

      <div className="flex-1 overflow-y-auto px-4 py-6">
        {/* Always-on pipeline intelligence — honest forecast + cohorts,
            computed from real data (no AI generation, no waiting). */}
        <div className="grid gap-4 lg:grid-cols-2">
          <RevenueForecast />
          <CohortInsights />
        </div>

        {/* On-demand AI reports */}
        <h2
          className="mt-8 mb-3 text-[12px] font-semibold uppercase tracking-wider"
          style={{ color: "var(--color-text-tertiary)" }}
        >
          Generate a report
        </h2>
        {/* Report type cards */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {reportTypes.map((rt) => {
            const Icon = rt.icon;
            const isLoading = loading === rt.type;
            const isScheduled = scheduleSuccess === rt.type;
            return (
              <Card
                key={rt.type}
                interactive
                onClick={() => !loading && generateReport(rt.type)}
                className={loading && !isLoading ? "opacity-50 pointer-events-none" : ""}
              >
                <CardBody>
                  <div className="flex items-start justify-between">
                    <div
                      className="flex h-9 w-9 items-center justify-center rounded-lg"
                      style={{ background: "var(--color-accent-soft)" }}
                    >
                      <Icon size={18} style={{ color: "var(--color-accent)" }} />
                    </div>
                    <Badge variant={rt.badgeVariant}>{rt.badgeLabel}</Badge>
                  </div>
                  <h3
                    className="mt-3 text-[14px] font-semibold"
                    style={{ color: "var(--color-text-primary)" }}
                  >
                    {rt.title}
                  </h3>
                  <p
                    className="mt-1 text-[12px] leading-relaxed"
                    style={{ color: "var(--color-text-tertiary)" }}
                  >
                    {rt.description}
                  </p>
                  <div className="mt-3 flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      loading={isLoading}
                      disabled={!!loading}
                      onClick={(e) => {
                        e.stopPropagation();
                        if (!loading) generateReport(rt.type);
                      }}
                    >
                      {isLoading ? "Generating..." : "Generate"}
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      disabled={!!loading || schedulingType === rt.type}
                      onClick={(e) => {
                        e.stopPropagation();
                        scheduleWeekly(rt.type);
                      }}
                    >
                      {schedulingType === rt.type ? (
                        <Loader2 size={12} className="animate-spin" />
                      ) : isScheduled ? (
                        <Check size={12} />
                      ) : (
                        <Timer size={12} />
                      )}
                      <span className="ml-1">
                        {isScheduled ? "Scheduled" : "Schedule weekly"}
                      </span>
                    </Button>
                  </div>
                </CardBody>
              </Card>
            );
          })}
        </div>

        {/* Loading indicator with progress steps */}
        {loading && (
          <div className="mt-8">
            <Card>
              <CardBody>
                <div className="flex items-center gap-3 mb-4">
                  <Loader2
                    size={18}
                    className="animate-spin shrink-0"
                    style={{ color: "var(--color-accent)" }}
                  />
                  <span
                    className="text-[14px] font-medium"
                    style={{ color: "var(--color-text-primary)" }}
                  >
                    Generating {reportTypes.find((r) => r.type === loading)?.title || "report"}...
                  </span>
                </div>
                <div className="space-y-2">
                  {PROGRESS_STEPS.map((step, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-2 text-[12px] transition-opacity duration-300"
                      style={{
                        color: i <= progressStep ? "var(--color-text-secondary)" : "var(--color-text-muted)",
                        opacity: i <= progressStep ? 1 : 0.4,
                      }}
                    >
                      {i < progressStep ? (
                        <Check size={12} className="shrink-0 text-emerald-400" />
                      ) : i === progressStep ? (
                        <Loader2 size={12} className="shrink-0 animate-spin" style={{ color: "var(--color-accent)" }} />
                      ) : (
                        <div className="h-3 w-3 shrink-0" />
                      )}
                      {step}
                    </div>
                  ))}
                </div>
                {/* Progress bar */}
                <div className="mt-4 h-1.5 w-full rounded-full bg-[var(--color-bg-page)]">
                  <div
                    className="h-1.5 rounded-full transition-all duration-500"
                    style={{
                      width: `${((progressStep + 1) / PROGRESS_STEPS.length) * 100}%`,
                      background: "var(--color-accent)",
                    }}
                  />
                </div>
              </CardBody>
            </Card>
          </div>
        )}

        {/* Error */}
        {error && (
          <Card className="mt-6">
            <CardBody>
              <p className="text-[13px]" style={{ color: "var(--color-error)" }}>
                {error}
              </p>
            </CardBody>
          </Card>
        )}

        {/* Report display */}
        {report && !loading && (
          <div className="mt-8 space-y-6">
            {/* Title & summary + action buttons */}
            <Card>
              <CardBody>
                <div className="flex items-start justify-between">
                  <div className="flex-1 min-w-0">
                    <h2
                      className="text-[18px] font-bold"
                      style={{ color: "var(--color-text-primary)" }}
                    >
                      {report.title}
                    </h2>
                    <p
                      className="mt-2 text-[13px] leading-relaxed"
                      style={{ color: "var(--color-text-secondary)" }}
                    >
                      {report.summary}
                    </p>
                  </div>
                  <div className="flex items-center gap-2 ml-4 shrink-0">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={copyAsMarkdown}
                    >
                      {copied ? (
                        <>
                          <Check size={12} />
                          <span className="ml-1">Copied</span>
                        </>
                      ) : (
                        <>
                          <ClipboardCopy size={12} />
                          <span className="ml-1">Copy as markdown</span>
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              </CardBody>
            </Card>

            {/* Metrics grid */}
            {report.metrics.length > 0 && (
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {report.metrics.map((metric, i) => (
                  <Card key={i}>
                    <CardBody className="text-center">
                      <p
                        className="text-[11px] font-medium uppercase tracking-wider"
                        style={{ color: "var(--color-text-tertiary)" }}
                      >
                        {metric.label}
                      </p>
                      <p
                        className="mt-1 text-[20px] font-bold"
                        style={{ color: "var(--color-text-primary)" }}
                      >
                        {metric.value}
                      </p>
                    </CardBody>
                  </Card>
                ))}
              </div>
            )}

            {/* Sections */}
            {report.sections.map((section, i) => (
              <Card key={i}>
                <CardBody>
                  <h3
                    className="text-[14px] font-semibold"
                    style={{ color: "var(--color-text-primary)" }}
                  >
                    {section.heading}
                  </h3>
                  <p
                    className="mt-2 whitespace-pre-line text-[13px] leading-relaxed"
                    style={{ color: "var(--color-text-secondary)" }}
                  >
                    {section.content}
                  </p>
                </CardBody>
              </Card>
            ))}

            {/* Recommendations */}
            {report.recommendations.length > 0 && (
              <Card>
                <CardBody>
                  <h3
                    className="text-[14px] font-semibold"
                    style={{ color: "var(--color-text-primary)" }}
                  >
                    Recommendations
                  </h3>
                  <ul className="mt-3 space-y-2">
                    {report.recommendations.map((rec, i) => (
                      <li
                        key={i}
                        className="flex items-start gap-2 text-[13px] leading-relaxed"
                        style={{ color: "var(--color-text-secondary)" }}
                      >
                        <span
                          className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full"
                          style={{ background: "var(--color-accent)" }}
                        />
                        {rec}
                      </li>
                    ))}
                  </ul>
                </CardBody>
              </Card>
            )}
          </div>
        )}

        {/* Report History */}
        {history.length > 0 && (
          <div className="mt-8">
            <h2
              className="text-[12px] font-semibold uppercase tracking-wider mb-3"
              style={{ color: "var(--color-text-tertiary)" }}
            >
              Recent Reports
            </h2>
            <div className="space-y-2">
              {history.map((entry) => {
                const rt = reportTypes.find((r) => r.type === entry.type);
                const Icon = rt?.icon || FileBarChart;
                const date = new Date(entry.generatedAt);
                const timeAgo = getTimeAgo(date);
                const isActive = report === entry.report;
                return (
                  <Card
                    key={entry.id}
                    interactive
                    onClick={() => loadFromHistory(entry)}
                    className={isActive ? "ring-1 ring-[var(--color-accent)]" : ""}
                  >
                    <div className="flex items-center gap-3 px-4 py-3">
                      <Icon size={14} style={{ color: "var(--color-text-muted)" }} />
                      <div className="flex-1 min-w-0">
                        <p
                          className="text-[13px] font-medium truncate"
                          style={{ color: "var(--color-text-primary)" }}
                        >
                          {entry.title}
                        </p>
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        <Clock size={11} style={{ color: "var(--color-text-muted)" }} />
                        <span
                          className="text-[11px]"
                          style={{ color: "var(--color-text-muted)" }}
                        >
                          {timeAgo}
                        </span>
                      </div>
                      {rt && <Badge variant={rt.badgeVariant} size="sm">{rt.badgeLabel}</Badge>}
                    </div>
                  </Card>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function getTimeAgo(date: Date): string {
  const now = Date.now();
  const diff = now - date.getTime();
  const minutes = Math.floor(diff / 60000);
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return date.toLocaleDateString([], { month: "short", day: "numeric" });
}
