-- Editable, per-tenant call script (replaces the hardcoded SECTOR_SCRIPTS in
-- lib/call-mode/call-scripts.ts). One default row per tenant (sector = ''),
-- optional per-sector variants. Generated by LLM from the tenant's product +
-- ICP, then editable by the rep. Idempotent.
CREATE TABLE IF NOT EXISTS call_scripts (
  id               TEXT PRIMARY KEY,
  tenant_id        TEXT NOT NULL REFERENCES tenants(id),
  sector           TEXT NOT NULL DEFAULT '',
  opener           TEXT NOT NULL,
  problems         JSONB NOT NULL DEFAULT '[]'::jsonb,
  permission_check TEXT NOT NULL,
  booking_ask      TEXT NOT NULL,
  guidance         JSONB NOT NULL DEFAULT '[]'::jsonb,
  origin           TEXT NOT NULL DEFAULT 'edited',
  updated_by       TEXT REFERENCES users(id),
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS call_scripts_tenant_sector_idx ON call_scripts (tenant_id, sector);
